# Generated by Django 3.1.7 on 2021-03-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberID', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('bloodGroup', models.CharField(default='Not Provided', max_length=20)),
                ('maritalStatus', models.CharField(default='Not Provided', max_length=50)),
                ('country', models.CharField(default='Not Provided', max_length=100)),
                ('stateOfOrigin', models.CharField(default='Not Provided', max_length=200)),
                ('town', models.CharField(default='Not Provided', max_length=200)),
                ('LGA', models.CharField(default='Not Provided', max_length=100)),
                ('nextOfKin', models.CharField(default='Not Provided', max_length=200)),
                ('highestQual', models.CharField(default='Not Provided', max_length=200)),
                ('occupation', models.CharField(default='Not Provided', max_length=200)),
                ('proffession', models.CharField(default='Not Provided', max_length=200)),
                ('positionHeld', models.CharField(default='Not Provided', max_length=200)),
                ('residentialAddress', models.TextField(default='Not Provided', max_length=800)),
                ('officeAddress', models.TextField(default='Not Provided', max_length=800)),
                ('otherInfo', models.TextField(default='Not Provided', max_length=800)),
                ('profileImg', models.ImageField(default='static/img/passportplaceholder.jpg', upload_to='profilePics')),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'Members_tb',
            },
        ),
    ]
