# Generated by Django 3.1.7 on 2021-03-02 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=550)),
                ('address', models.TextField(max_length=800, verbose_name='Organization Address')),
                ('email', models.CharField(max_length=100, verbose_name='Organization Email')),
                ('contact', models.CharField(max_length=50, verbose_name='Organization Contact')),
                ('logo', models.ImageField(blank=True, default='media/orgLogos/memberPlus.jpg', upload_to='orgLogos')),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='orgID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.organization'),
            preserve_default=False,
        ),
    ]
