# Generated by Django 3.1.7 on 2021-03-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20210302_1932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Organizations',
        ),
    ]
