# Generated by Django 3.1.7 on 2021-03-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20210302_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizations',
            name='address',
            field=models.TextField(blank=True, max_length=800, verbose_name='Organization Address'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='contact',
            field=models.CharField(blank=True, max_length=50, verbose_name='Organization Contact'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Organization Email'),
        ),
    ]
